/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Messaging Protocol Definition Engine
 * Source Origin: KillianLucas/open-interpreter
 * Isolated clean-room architectural engine extracted by Engine Harvester
 */

// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the content structure for messages sent as input to an agent.
 * It can be either plain text or encrypted content.
 */
export type AgentMessageInputContent = { "type": "input_text", text: string, } | { "type": "encrypted_content", encrypted_content: string, };

/**
 * Defines the type for an agent's path within the system, represented as a string.
 */
export type AgentPath = string;

/**
 * Defines the structure for information about a connected client.
 * Includes name, an optional title, and its version.
 */
export type ClientInfo = { name: string, title: string | null, version: string, };

/**
 * Defines the structure for notifications sent from the server to the client.
 * Currently includes an 'initialized' notification.
 */
export type ClientNotification = { "method": "initialized" };
